
--1. List all orders where the OTIF_Flag is 0 (i.e., deliveries that were not on-time-in-full).


SELECT *
FROM fact_orders
WHERE otif_flag = 0;

--2. Find all products that belong to the "Beverages" category.


SELECT *
FROM dim_product
WHERE category = 'Beverages';

--3. Show all suppliers with a RiskTier of "High".


SELECT *
FROM dim_supplier
WHERE risktier = 'High';

--4. Get the top 10 orders with the highest Revenue, sorted in descending order.


SELECT *
FROM fact_orders
ORDER BY revenue DESC
LIMIT 10;



--5. Find the total Revenue and GrossProfit generated by each Channel.


SELECT channel,
       SUM(revenue) AS total_revenue,
       SUM(grossprofit) AS total_grossprofit
FROM fact_orders
GROUP BY channel
ORDER BY total_revenue DESC;

--6. Calculate the average OTIF_Flag (i.e., OTIF %) for each WarehouseID.


SELECT warehouseid,
       AVG(otif_flag) AS otif_rate
FROM fact_orders
GROUP BY warehouseid
ORDER BY otif_rate;

--7. Find the number of orders and total WasteQty for each ProductID, showing only products with total waste greater than 20.


SELECT productid,
       COUNT(*) AS total_orders,
       SUM(wasteqty) AS total_waste
FROM fact_orders
GROUP BY productid
HAVING SUM(wasteqty) > 20
ORDER BY total_waste DESC;

--8. Calculate the total StockoutFlag count per WarehouseID from the Inventory_Snapshots table.


SELECT warehouseid,
       SUM(stockoutflag) AS total_stockouts
FROM inventory_snapshots
GROUP BY warehouseid
ORDER BY total_stockouts DESC;



--9. Write a query to show OrderID, ProductName, Category, and Revenue by joining Fact_Orders with Dim_Product.


SELECT f.orderid,
       p.productname,
       p.category,
       f.revenue
FROM fact_orders f
JOIN dim_product p ON f.productid = p.productid;

--10. Find the total Revenue generated by each SupplierName, joining Fact_Orders with Dim_Supplier.


SELECT s.suppliername,
       SUM(f.revenue) AS total_revenue
FROM fact_orders f
JOIN dim_supplier s ON f.supplierid = s.supplierid
GROUP BY s.suppliername
ORDER BY total_revenue DESC;

--11. List all orders along with the customer's CustomerSegment and SalesRegion, joining Fact_Orders with Dim_Customer.


SELECT f.orderid,
       c.customersegment,
       c.salesregion,
       f.revenue
FROM fact_orders f
JOIN dim_customer c ON f.customerid = c.customerid;

--12. Find the average LateDays for each WarehouseName, joining Fact_Orders with Dim_Warehouse.


SELECT w.warehousename,
       AVG(f.latedays) AS avg_late_days
FROM fact_orders f
JOIN dim_warehouse w ON f.warehouseid = w.warehouseid
GROUP BY w.warehousename
ORDER BY avg_late_days DESC;



--13. Find products whose total Revenue is above the average Revenue across all products (use a subquery or CTE).


WITH product_revenue AS (
    SELECT productid, SUM(revenue) AS total_revenue
    FROM fact_orders
    GROUP BY productid
)
SELECT *
FROM product_revenue
WHERE total_revenue > (SELECT AVG(total_revenue) FROM product_revenue)
ORDER BY total_revenue DESC;

--14. Rank suppliers by their ReliabilityPct using a window function (RANK() or DENSE_RANK()).


SELECT suppliername,
       reliabilitypct,
       RANK() OVER (ORDER BY reliabilitypct DESC) AS reliability_rank
FROM dim_supplier;

--15. For each WarehouseID, find the month (SnapshotMonth) with the highest ExpiredQty using a window function.


WITH ranked AS (
    SELECT warehouseid,
           snapshotmonth,
           expiredqty,
           RANK() OVER (PARTITION BY warehouseid ORDER BY expiredqty DESC) AS rnk
    FROM inventory_snapshots
)
SELECT warehouseid, snapshotmonth, expiredqty
FROM ranked
WHERE rnk = 1;

--16. Calculate a running total of Revenue over OrderDate (cumulative revenue over time) using SUM() OVER (ORDER BY ...).


SELECT orderdate,
       revenue,
       SUM(revenue) OVER (ORDER BY orderdate) AS running_revenue
FROM fact_orders
ORDER BY orderdate;



--17. Which channel has the best OTIF rate but the lowest revenue — is there a trade-off worth investigating?


SELECT channel,
       AVG(otif_flag) AS otif_rate,
       SUM(revenue) AS total_revenue
FROM fact_orders
GROUP BY channel
ORDER BY otif_rate DESC, total_revenue ASC;

--18 Find suppliers whose ReliabilityPct is above average but whose AvgDefectRate is also above the median — i.e., suppliers that look reliable on paper but still carry above-average defect risk.


SELECT suppliername,
       reliabilitypct,
       avgdefectrate
FROM dim_supplier
WHERE reliabilitypct > (SELECT AVG(reliabilitypct) FROM dim_supplier)
ORDER BY avgdefectrate DESC;

--19. Find the top 5 products contributing the most to GrossProfit, along with their Category.


SELECT p.productname,
       p.category,
       SUM(f.grossprofit) AS total_grossprofit
FROM fact_orders f
JOIN dim_product p ON f.productid = p.productid
GROUP BY p.productname, p.category
ORDER BY total_grossprofit DESC
LIMIT 5;

--20. Compare Revenue and GrossProfit month-over-month to spot any seasonal patterns (use Dim_Date for month grouping).


SELECT d.year,
       d.monthno,
       d.monthname,
       SUM(f.revenue) AS total_revenue,
       SUM(f.grossprofit) AS total_grossprofit
FROM fact_orders f
JOIN dim_date d ON f.orderdate = d.date
GROUP BY d.year, d.monthno, d.monthname
ORDER BY d.year, d.monthno;